### ISSUE TITLE
Header does not collapse when using a nested StackNavigator (react-navigation v5)

### ISSUE THREAD

**Issue by RoderickJDunn** [benevbright/react-navigation-collapsible#110]
## Information
- react-native version: 0.61
- react-navigation version: 5
- react-navigation-collapsible version: 5.0.0 
- Platform (iOS/Android): iOS
- react-native init or Expo:  react-native init

## Detail
I don't know if this is a bug or simply not supported behaviour, but I can't get my header to collapse when the screen is part of a nested Stack Navigator. The header is completely static while scrolling on such screens. Below is a minimal repro of the issue, adapted from the example code. When 'DefaultHeaderScreen' is accessed from the root stack (tap 'Sample1: DefaultHeader') the header collapses when scrolling as expected. However, if you tap 'Sample2: NestedStack', which navigates to a new Stack containing 'DefaultHeaderScreen' as a screen, the header does not collapse when scrolling.

```
import React from 'react';
import {Animated, TouchableOpacity, View, Text} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createStackNavigator} from '@react-navigation/stack';
import {
    createCollapsibleStack,
    useCollapsibleStack,
} from 'react-navigation-collapsible';

const data: number[] = [];
for (let i = 0; i < 100; i++) {
    data.push(i);
}

const samples = [
    {title: 'Sample1: DefaultHeader', routeName: 'WithDefaultHeader'},
    {title: 'Sample2: NestedStack', routeName: 'NestedStack'},
    {title: 'Sample3: Sub Header', routeName: 'WithSubHeader'},
];

const DefaultHeaderScreen = ({navigation}: ScreenProps) => {
    const {
        onScroll,
        containerPaddingTop,
        scrollIndicatorInsetTop,
    } = useCollapsibleStack();

    console.log('onScroll', onScroll);
    console.log('containerPaddingTop', containerPaddingTop);
    console.log('scrollIndicatorInsetTop', scrollIndicatorInsetTop);

    return (
        <Animated.FlatList
            data={data}
            onScroll={onScroll}
            contentContainerStyle={{paddingTop: containerPaddingTop}}
            scrollIndicatorInsets={{top: scrollIndicatorInsetTop}}
            renderItem={({item}: any) => (
                <TouchableOpacity
                    onPress={() => navigation.navigate('Detail')}
                    style={{
                        width: '100%',
                        height: 50,
                        alignItems: 'center',
                        justifyContent: 'center',
                        borderBottomColor: 'gray',
                        borderBottomWidth: 1,
                    }}>
                    <Text
                        style={{
                            fontSize: 22,
                        }}>
                        {item}
                    </Text>
                </TouchableOpacity>
            )}
            keyExtractor={(item: any) => item.toString()}
        />
    );
};

function HomeScreen({navigation}: ScreenProps) {
    return (
        <View style={{flex: 1, paddingTop: 50, alignItems: 'center'}}>
            {samples.map(sample => (
                <Text
                    key={sample.title}
                    style={{margin: 15}}
                    onPress={() => {
                        navigation.navigate(sample.routeName);
                    }}>
                    {sample.title}
                </Text>
            ))}
        </View>
    );
}

const Stack = createStackNavigator();

function NestedStack() {
    return (
        <Stack.Navigator
            screenOptions={{
                headerStyle: {
                    backgroundColor: '#f002',
                },
            }}>
            {createCollapsibleStack(
                <Stack.Screen
                    name="WithDefaultHeaderNested"
                    component={DefaultHeaderScreen}
                    options={{
                        headerStyle: {backgroundColor: 'green'},
                        headerTintColor: 'white',
                        title: 'Regular Header',
                    }}
                />,
                {
                    collapsedColor: 'red',
                },
            )}
        </Stack.Navigator>
    );
}

function App() {
    return (
        <NavigationContainer>
            <Stack.Navigator
                screenOptions={{
                    headerStyle: {
                        backgroundColor: '#f002',
                    },
                }}>
                <Stack.Screen
                    name="Home"
                    component={HomeScreen}
                    options={{
                        title: 'react-navigation-collapsible',
                    }}
                />
                <Stack.Screen
                    name="NestedStack"
                    component={NestedStack}
                    options={{
                        headerStyle: {backgroundColor: 'green'},
                        headerTintColor: 'white',
                        title: 'Collapsible (Nested)',
                        header: () => null,
                    }}
                />
                {createCollapsibleStack(
                    <Stack.Screen
                        name="WithDefaultHeader"
                        component={DefaultHeaderScreen}
                        options={{
                            headerStyle: {backgroundColor: 'green'},
                            headerTintColor: 'white',
                            title: 'Regular Header',
                        }}
                    />,
                )}

                {/* <Stack.Screen
                    name="Detail"
                    component={DetailScreen}
                    options={{
                        title: 'Detail Screen',
                    }}
                /> */}
            </Stack.Navigator>
        </NavigationContainer>
    );
}

export default App;
```

 I'd appreciate any help... Thanks!

**Comment by JackShannon** [comment]
I have found a similar issue when I nest the Stack.Navigator (in the example) inside a Tab.Navigator. The header doesn't collapse. Trying to figure out what is going on as the SubHeader example still works when nested, so translateY value is being animated correctly.

**Comment by benevbright** [comment]
Thanks for your examples. 
I've tested it and indeed it doesn't work. 

After some investigating, 
https://github.com/benevbright/react-navigation-collapsible/blob/e4c4b528bd3e9c647441e33674410f321ea8b4d5/src/createCollapsibleStack.tsx#L32
It's called two times on beginning and it's called every time the device rotates when it's nested stack, whereas it's called only one time and doesn't get called when rotating when it's not nested stack. 
I think this difference makes it reset. 

I like to try such a thing as `useRef` to store reference but I can't because this function is not a component.

Can't you avoid the nested stack? Because I don't think it's a good idea regardless of this issue.

**Comment by helloiamlukas** [comment]
I have the same problem. My structure looks like this:

```jsx
<NavigationContainer>
  <BottomTab.Navigator>
    <BottomTab.Screen>
      <Stack.Navigator>
        <Stack.Screen/>
        <Stack.Screen/>
      </Stack.Navigator>
    </BottomTab.Screen>
    <BottomTab.Screen>
      <Stack.Navigator>
        <Stack.Screen/>
        <Stack.Screen/>
      </Stack.Navigator>
    </BottomTab.Screen>
  </BottomTab.Navigator>
</NavigationContainer>
```

> Can't you avoid the nested stack? Because I don't think it's a good idea regardless of this issue.

I would argue this is a very common pattern when using (bottom) tabs. Even the official [Expo React Native Starter Template](https://github.com/expo/expo/tree/master/templates/expo-template-tabs) is nesting stacks.

Would really love to see support for this 😊

**Comment by benevbright** [comment]
Thanks @Steven-Sanseau . It's resolved in v5.0.1.

**Comment by Steven-Sanseau** [comment]
Thanks for your reactivity @benevbright

**Comment by ozerty** [comment]
Hi @benevbright I still have the same issue with a custom header component.
I have a weird behavior.
This is my navigation tree :

```
<NavigationContainer>
  <BottomTab.Navigator>
    <BottomTab.Screen>
      <Stack.Navigator>
        {createCollapsibleStack(<Stack.Screen/>)}
        {createCollapsibleStack(<Stack.Screen/>)}
      </Stack.Navigator>
    </BottomTab.Screen>
  </BottomTab.Navigator>
</NavigationContainer>
```

When the App loads, `containerPaddingTop` and  `scrollIndicatorInsetTop` are equals to 0.
Side effect : my screen goes behind the header.

When I just refresh the app, `containerPaddingTop` and  `scrollIndicatorInsetTop`  values are corretly defined.
No side effect.

Am I missing something ?

Thanks guys.

**Comment by benevbright** [comment]
Hi @ozerty how do your stack’s options look like? I need an example to reproduce. 
And on which platform do you have a problem?

**Comment by ozerty** [comment]
Hi @benevbright I finally found my problem.
It was my new navigation tree where I set the `Navigator` during user's authentication.

Not working correctly with `react-navigation-collapsible`.

```
<NavigationContainer>
  {authstate.authSuccess && (
    <BottomTab.Navigator>
      <BottomTab.Screen>
        <Stack.Navigator>
          {createCollapsibleStack(<Stack.Screen/>)}
        </Stack.Navigator>
      </BottomTab.Screen>
    </BottomTab.Navigator>
  ) : (
    <Stack.Navigator> // Auth Stack
      <Stack.Screen/>
    </Stack.Navigator>
  )}
</NavigationContainer>
```

Working like a charm with `react-navigation-collapsible`.

```
<NavigationContainer>
  <BottomTab.Navigator>
    {authstate.authSuccess && (
      <BottomTab.Screen>
        <Stack.Navigator>
          {createCollapsibleStack(<Stack.Screen/>)}
        </Stack.Navigator>
      </BottomTab.Screen>
    ) : (
      <BottomTab.Screen>
        <Stack.Navigator> // Auth Stack
          <Stack.Screen/>
        </Stack.Navigator>
      </BottomTab.Screen>
    )}
  </BottomTab.Navigator>
</NavigationContainer>
```

**Comment by benevbright** [comment]
Cool 👍👍 @ozerty Thanks.
